name: Aykut Yilmaz
description: Official Homepage of Aykut Yilmaz.
url: https://aykut.ga

social:
  email: mail@aykut.ga
  facebook: aykuxt
  twitter: aykuxt
  instagram: aykuxt
  snapchat: aykuuut78
  googleplus: +AykutYilmaz
  youtube: AykutYilmaz
  github: aykut78
  telegram: aykxt

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

permalink: none
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
