name: Aykut Yilmaz
description: Official Homepage of Aykut Yilmaz.
url: https://aykut.ga

social:
  email: mail@aykut.ga
  facebook: aykuxt
  twitter: aykuxt
  instagram: aykuxt
  snapchat: aykuuut78
  googleplus: +AykutYilmaz # anything in your profile username that comes after plus.google.com/
  youtube: AykutYilmaz # channel/<your_long_string> or user/<user-name>
  github: aykut78
  telegram: aykxt

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

permalink: none
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plug-ins
plugins:

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
